<?php  
include "ADM_SESS.php";
require_once('../worldpay-lib-php/init.php');
use \Worldpay\Worldpay;

use PHPMailer\PHPMailer\PHPMailer;
//use PHPMailer\PHPMailer\SMTP;
use PHPMailer\PHPMailer\Exception;
require '../phpmailer/src/Exception.php';
//require '../phpmailer/src/SMTP.php';
require '../phpmailer/src/PHPMailer.php';
//$err = array(FALSE, FALSE, FALSE);
$ermsg = "";
date_default_timezone_set("Europe/London");
	$p = $db->prepare("SELECT * FROM `orders` WHERE `oid`=?");
	$p->execute([$_POST['zyid']]);
	if($r = $p->fetch()){
		//-- generated by robotcoding1_SEYOL --//
		$zybfn = $r['bfn'];
		$zybln = $r['bln'];
		$zybad1 = $r['bad1'];
		$zybad2 = $r['bad2'];
		$zybad3 = $r['bad3'];
		$zybpz = $r['bpz'];
		$zybzp = $r['bzp'];
		$zybct = $r['bct'];
		$zybst = $r['bst'];
		$zybem = $r['bem'];
		$zysfn = $r['sfn'];
		$zysln = $r['sln'];
		$zysad1 = $r['sad1'];
		$zysad2 = $r['sad2'];
		$zysad3 = $r['sad3'];
		$zyspz = $r['spz'];
		$zyszp = $r['szp'];
		$zysct = $r['sct'];
		$zysst = $r['sst'];
		$zysem = $r['sem'];
		$zydt = $r['dt'];
		$pay = $r['pay'];
		$code = $r['code'];
		$amount = $r['tpr'];
	}
	$arr_status = array("Not Completed","Paid","Refund");
	if(isset($_POST['post'])){
		/// payments
		$worldpay = new Worldpay('T_S_aed4cebd-8f7d-48e7-ae54-f932343b4996');
		
		try {
		    $ok = $worldpay->refundOrder($_POST['code']);
		    if($ok) echo 555555;
		    else echo 22222;
		    
		   /* if ($response['paymentStatus'] === 'SUCCESS') {
		    	
		    } else {
		        throw new WorldpayException(print_r($response, true));
		    }*/
		} catch (WorldpayException $e) {
		    $ermsg.= 'Error code: ' . $e->getCustomCode() . '
		    HTTP status code:' . $e->getHttpStatusCode() . '
		    Error description: ' . $e->getDescription()  . ' 
		    Error message: ' . $e->getMessage();
		} catch (Exception $e) {
		    $ermsg.= 'Error message: '. $e->getMessage();
		}
		/// payments
	}
 ?>
	<div id="zy1">
		<?php if(!empty($ermsg)) echo '<p class="x3ko">',$ermsg,'</p>'; ?>
		<h1>View Order</h1>
		<?php //-- generated by robotcoding4_SEYOL --// ?>
		<form action="" method="post" enctype="multipart/form-data" id="zf1">
		<h2>Order Details</h2>
		<fieldset class="x3fs">
			<label class="x3lb">
				<span class="x3s">Order Status</span>
				<div class="x3d">
				<span class="x3in"><?php echo $arr_status[$r['pay']]; ?></span>
				</div>
			</label>
			<label class="x3lb">
				<span class="x3s">Transaction Code</span>
				<div class="x3d">
				<input type="hidden" value="<?php echo $code; ?>" name="code">
				<span class="x3in"><?php echo $code; ?></span>
				</div>
			</label>
			<label class="x3lb">
				<span class="x3s">Order Amount</span>
				<div class="x3d">
				<span class="x3in"><?php echo $amount; ?></span>
				</div>
			</label>
			<?php /*
			<div class="x3lb">
				<span class="x3s">&nbsp;</span>
				<div class="x3d x9e">
				<input type="button" value="Refund" class="x3in x3in2" name="zysent" id="zysent">
				<input type="hidden" value="1" name="post">
				<input type="hidden" id="zyid" name="zyid" value="<?php echo $_POST['zyid']; ?>">
				</div>
			</div>
			*/ ?>
		</fieldset>	
		<h2>Shipping Details</h2>
			<fieldset class="x3fs">
			<label class="x3lb">
				<span class="x3s">First Name</span>
				<div class="x3d">
				<span class="x3in"><?php echo $zysfn; ?></span>
				</div>
			</label>
			<label class="x3lb">
				<span class="x3s">Last Name</span>
				<div class="x3d">
				<span class="x3in"><?php echo $zysln; ?></span>
				</div>
			</label>
			<label class="x3lb">
				<span class="x3s">Address</span>
				<div class="x3d">
				<span class="x3in"><?php echo $zysad1,'<br>',$zysad2,'<br>',$zysad3; ?></span>
				</div>
			</label>
			<label class="x3lb">
				<span class="x3s">Phone No</span>
				<div class="x3d">
				<span class="x3in"><?php echo $zyspz; ?></span>
				</div>
			</label>
			<label class="x3lb">
				<span class="x3s">Zip Code</span>
				<div class="x3d">
				<span class="x3in"><?php echo $zyszp; ?></span>
				</div>
			</label>
			<label class="x3lb">
				<span class="x3s">City</span>
				<div class="x3d">
				<span class="x3in"><?php echo $zysct; ?></span>
				</div>
			</label>
			<label class="x3lb">
				<span class="x3s">State</span>
				<div class="x3d">
				<span class="x3in"><?php echo $zysst; ?></span>
				</div>
			</label>
			<label class="x3lb">
				<span class="x3s">Email</span>
				<div class="x3d">
				<span class="x3in"><?php echo $zysem; ?></span>
				</div>
			</label>
			</fieldset>
			<h2>Billing Details</h2>
			<fieldset class="x3fs">
				<label class="x3lb">
				<span class="x3s">First Name</span>
				<div class="x3d">
				<span class="x3in"><?php echo $zybfn; ?></span>
				</div>
			</label>
			<label class="x3lb">
				<span class="x3s">Last Name</span>
				<div class="x3d">
				<span class="x3in"><?php echo $zybln; ?></span>
				</div>
			</label>
			<label class="x3lb">
				<span class="x3s">Address</span>
				<div class="x3d">
				<span class="x3in"><?php echo $zybad1,'<br>',$zybad2,'<br>',$zybad3; ?></span>
				</div>
			</label>
			<label class="x3lb">
				<span class="x3s">Phone No</span>
				<div class="x3d">
				<span class="x3in"><?php echo $zybpz; ?></span>
				</div>
			</label>
			<label class="x3lb">
				<span class="x3s">Zip Code</span>
				<div class="x3d">
				<span class="x3in"><?php echo $zybzp; ?></span>
				</div>
			</label>
			<label class="x3lb">
				<span class="x3s">City</span>
				<div class="x3d">
				<span class="x3in"><?php echo $zybct; ?></span>
				</div>
			</label>
			<label class="x3lb">
				<span class="x3s">State</span>
				<div class="x3d">
				<span class="x3in"><?php echo $zybst; ?></span>
				</div>
			</label>
			<label class="x3lb">
				<span class="x3s">Email</span>
				<div class="x3d">
				<span class="x3in"><?php echo $zybem; ?></span>
				</div>
			</label>
			<label class="x3lb">
				<span class="x3s">Date</span>
				<div class="x3d">
				<span class="x3in"><?php echo $zydt; ?></span>
				</div>
			</label>
			</fieldset>
		</form>
	</div>
