<?php
include "ADM_SESS.php";

$imageError = "";
$OK = FALSE;
function uploadImage($file, $targetDir = '/var/www/html/cloths/public/slides/', $maxWidth = 1200, $maxHeight = 400) {
    // Check if file was uploaded without errors
    if (isset($file) && $file['error'] == 0) {
        $fileType = pathinfo($file['name'], PATHINFO_EXTENSION);
        $fileName = date('YmdHis') . '_' . rand(1000, 9999) . '.' . $fileType;
        $targetFilePath = $targetDir . $fileName;
        $fileType = pathinfo($targetFilePath, PATHINFO_EXTENSION);

        // Allow certain file formats
        $allowedTypes = array('jpg', 'jpeg', 'png', 'gif');
        if (in_array(strtolower($fileType), $allowedTypes)) {
            // Check if file is a valid image
            list($width, $height) = getimagesize($file['tmp_name']);
            if ($width <= $maxWidth && $height <= $maxHeight) {
                // Check if file already exists
                if (!file_exists($targetFilePath)) {
                    // Move the file to the target directory
                    if (move_uploaded_file($file['tmp_name'], $targetFilePath)) {
                        return [true,$fileName];
                    } else {
                        return [false,'Error: Unable to move the file.'];
                    }
                } else {
                    return [false,'Error: File already exists.'];
                }
            } else {
                return [false,'Error: Image dimensions should not exceed ' . $maxWidth . 'x' . $maxHeight . ' pixels.'];
            }
        } else {
            return [false,'Error: Only JPG, JPEG, PNG, and GIF files are allowed.'];
        }
    } else {
        return [false,'Error: ' . $file['error']];
    }
}



		if(isset($_POST['post'])){
            $uploadResult = uploadImage($_FILES['zyiz']);

            if ($uploadResult[0]) {
                $OK = $db->prepare("UPDATE `slides-new` SET `image`=? WHERE `id`=?")->execute([$uploadResult[1], $_POST['zyid']]);
            } else {
                $imageError = $uploadResult[1];
            }
		}


 ?>
	<div id="zy1">
		<?php if($OK) echo '<div class="x3ok">The slide has been updated</div>'; ?>
		<h1>Uplodad Your Slide Image</h1>
		<?php //-- generated by robotcoding4_SEYOL --// ?>
		<form action="" method="post" enctype="multipart/form-data" id="zf1">
			<div class="x3lb">
				<span class="x3s">Slide Banner Image (1200*600)</span>
				<div class="x3d">
					<input type="file" style="margin-bottom: 10px" class="x3in" name="zyiz" id="zyiz">
                    <span style="color: #9f7878;font-size: 18px;display: block;"><?php echo $imageError?></span>
				</div>
			</div>
			<div class="x3lb">
				<span class="x3s">&nbsp;</span>
				<div class="x3d x9e">
				<input type="button" class="x3in x3in2" value="Save" id="zysent">
				<input type="hidden" value="1" name="post">
				<input type="hidden" id="zyid" name="zyid" value="<?php echo $_POST["zyid"]; ?>">
				</div>
			</div>
			</fieldset>
		</form>
	</div>
