<?php  
include "ADM_SESS.php";
//$ermsg = "";
date_default_timezone_set("Europe/London");
$OK = FALSE;
function SE_optionsGen($array,$selected,$start=0,$end=0) {
	$end = $end==0 ? count($array)-1 : $end;
	$out = "";
	$selected = intval($selected);
	for($i=$start;$i<=$end;$i++){
		$out.= '<option value="'.$i.'"';
		$out.= $selected==$i ? ' selected ' : '' ;
		$out.= '>'.$array[$i].'</option>';
	}
	return $out;
}
$arr_status = array("Not Completed","Paid","Cancel");
	
	$p = $db->prepare("SELECT * FROM `orders` WHERE `oid`=?");
	$p->execute([$_POST['zyid']]);
	if($r = $p->fetch()){

		if(isset($_POST['post'])){
		
			//-- generated by robotcoding3_SEYOL --//
			$pay = $_POST['pay'];
						
			
			if(!in_array(TRUE, $err)){
				//-- generated by robotcoding2_SEYOL --//
					$OK = $db->prepare("UPDATE `orders` SET `pay`=? WHERE `oid`=?")->execute([$pay, $_POST['zyid']]);
			}
		}else{
			//-- generated by robotcoding1_SEYOL --//
				$pay = $r['pay'];
		}
	}else echo "No records found";

 ?>
	<div id="zy1">
		<?php if($OK) echo '<div class="x3ok">The slide has been updated</div>'; ?>
		<h1>Edit Item</h1>
		<?php //-- generated by robotcoding4_SEYOL --// ?>
		<form action="" method="post" enctype="multipart/form-data" id="zf1">
			<fieldset class="x3fs">
				<label class="x3lb">
					<span class="x3s">Order Status</span>
					<div class="x3d">
						<select class="x3in" name="pay" id="pay">
							<?php echo SE_optionsGen($arr_status, $pay); ?>
						</select>
					</div>
				</label>
				<div class="x3lb">
					<span class="x3s">&nbsp;</span>
					<div class="x3d x9e">
					<input type="button" class="x3in x3in2" value="Update" id="zysent">
					<input type="hidden" value="1" name="post">
					<input type="hidden" id="zyid" name="zyid" value="<?php echo $_POST["zyid"]; ?>">
					</div>
				</div>
			</fieldset>
		</form>
	</div>
<?php  
$msgno = "";
if(in_array(TRUE, $err)){
	$arrlen = count($err);
	for($i=0;$i<$arrlen;$i++){
		if($err[$i]) $msgno.=" e".$i;
	}
}
?>
<input type="hidden" id="msgno" value="<?php echo $msgno; ?>">