<?php  
include "ADM_SESS.php";
$err = array(FALSE, FALSE, FALSE, FALSE);
//$ermsg = "";
date_default_timezone_set("Europe/London");
$OK = FALSE;
function SE_optionsGen($array,$selected,$start=0,$end=0) {
	$end = $end==0 ? count($array)-1 : $end;
	$out = "";
	$selected = intval($selected);
	for($i=$start;$i<=$end;$i++){
		$out.= '<option value="'.$i.'"';
		$out.= $selected==$i ? ' selected ' : '' ;
		$out.= '>'.$array[$i].'</option>';
	}
	return $out;
}
	$arr_state = array('','Avon', 'Bedfordshire', 'Berkshire', 'Bristol, City of', 'Buckinghamshire', 'Cambridgeshire', 'Cheshire', 'Cleveland', 'Cornwall', 'Cumbria', 'Derbyshire', 'Devon', 'Dorset', 'Durham', 'East Sussex', 'Essex', 'Gloucestershire', 'Greater London', 'Greater Manchester', 'Hampshire (County of Southampton)', 'Hereford and Worcester', 'Herefordshire', 'Hertfordshire', 'Isle of Wight', 'Kent', 'Lancashire', 'Leicestershire', 'Lincolnshire', 'London', 'Merseyside', 'Middlesex', 'Norfolk', 'Northamptonshire', 'Northumberland', 'North Humberside', 'North Yorkshire', 'Nottinghamshire', 'Oxfordshire', 'Rutland', 'Shropshire', 'Somerset', 'South Humberside', 'South Yorkshire', 'Staffordshire', 'Suffolk', 'Surrey', 'Tyne and Wear', 'Warwickshire', 'West Midlands', 'West Sussex', 'West Yorkshire', 'Wiltshire', 'Worcestershire', 'Antrim', 'Armagh', 'Belfast, City of', 'Down', 'Fermanagh', 'Londonderry', 'Derry, City of', 'Tyrone', 'Aberdeen, City of', 'Aberdeenshire', 'Angus (Forfarshire)', 'Argyll', 'Ayrshire', 'Banffshire', 'Berwickshire', 'Bute', 'Caithness', 'Clackmannanshire', 'Cromartyshire', 'Dumfriesshire', 'Dunbartonshire (Dumbarton)', 'Dundee, City of', 'East Lothian (Haddingtonshire)', 'Edinburgh, City of', 'Fife', 'Glasgow, City of', 'Inverness-shire', 'Kincardineshire', 'Kinross-shire', 'Kirkcudbrightshire', 'Lanarkshire', 'Midlothian (County of Edinburgh)', 'Moray (Elginshire)', 'Nairnshire', 'Orkney', 'Peeblesshire', 'Perthshire', 'Renfrewshire', 'Ross and Cromarty', 'Ross-shire', 'Roxburghshire', 'Selkirkshire', 'Shetland (Zetland)', 'Stirlingshire', 'Sutherland', 'West Lothian (Linlithgowshire)', 'Wigtownshire', 'Clwyd', 'Dyfed', 'Gwent', 'Gwynedd', 'Mid Glamorgan', 'Powys', 'South Glamorgan', 'West Glamorgan');
	$p = $db->prepare("SELECT * FROM `users` WHERE `uid`=?");
	$p->execute([$_POST['zyid']]);
	if($r = $p->fetch()){

		if(isset($_POST['post'])){
	/*
		Errors
		=======================
		
		0 - Empty first name
		1 - Empty last name
		2 - Empty email name
		3 - Invalid email 
		4 - Email is already exist 

	*/		
			$err[0] = empty($_POST['zyfn']) ? TRUE : FALSE;
			$err[1] = empty($_POST['zyln']) ? TRUE : FALSE;
			$err[2] = empty($_POST['zyez']) ? TRUE : FALSE;
			
			$_POST['zyez'] = strtolower($_POST['zyez']);
			$_POST['zyez'] = filter_var($_POST['zyez'], FILTER_SANITIZE_EMAIL);
			if(!filter_var($_POST['zyez'],FILTER_VALIDATE_EMAIL)) $err[3]=TRUE;
			
			//-- generated by robotcoding3_SEYOL --//
			$zyfn = $_POST['zyfn'];
			$zyln = $_POST['zyln'];
			$zyez = $_POST['zyez'];
			$zypz = $_POST['zypz'];
			$zyad1 = $_POST['zyad1'];
			$zyad2 = $_POST['zyad2'];
			$zyad3 = $_POST['zyad3'];
			$zyct = $_POST['zyct'];
			$zyst = $_POST['zyst'];
			$zyzp = $_POST['zyzp'];
			$zyaz = $_POST['zyaz'];
			$zypw = $_POST['zypw'];
				
			if(!in_array(TRUE, $err) && $r['ez']!=$zyez){
				$p2 = $db->prepare("SELECT `uid` FROM `users` WHERE `ez`=?");
				$p2->execute(array($zyez));
				if($s = $p2->fetch()) $err[4] = TRUE;
			}

			if(!in_array(TRUE, $err)){
				if(!empty($zypw)) $zypw = password_hash($zypw, PASSWORD_DEFAULT);				
				else $zypw = $r['pw'];
				
				//-- generated by robotcoding2_SEYOL --//
				$OK = $db->prepare("UPDATE `users` SET `fn`=?, `ln`=?, `ez`=?, `pz`=?, `ad1`=?, `ad2`=?, `ad3`=?, `ct`=?, `st`=?, `zp`=?, `az`=?, `pw`=? WHERE `uid`=?")->execute([$zyfn, $zyln, $zyez, $zypz, $zyad1, $zyad2, $zyad3, $zyct, $zyst, $zyzp, $zyaz, $zypw, $_POST['zyid']]);
			}
		}else{
			//-- generated by robotcoding1_SEYOL --//
			$zyfn = $r['fn'];
			$zyln = $r['ln'];
			$zyez = $r['ez'];
			$zypz = $r['pz'];
			$zyad1 = $r['ad1'];
			$zyad2 = $r['ad2'];
			$zyad3 = $r['ad3'];
			$zyct = $r['ct'];
			$zyst = $r['st'];
			$zyzp = $r['zp'];
			$zyaz = $r['az'];
			$zypw = $r['pw'];
		}
	}else echo "No records found";

 ?>


	<div id="zy1">
		<?php if($OK) echo '<div class="x3ok">User updated successfully.</div>'; ?>
		<h1>Edit User</h1>
		<form action="" method="post" enctype="multipart/form-data" id="zf1">
		<fieldset class="x3fs">
			<label class="x3lb">
				<span class="x3s">First Name *</span>
				<div class="x3d">
					<input type="text" class="x3in" name="zyfn" value="<?php echo $zyfn; ?>" id="zyfn">
				</div>
			</label>
			<label class="x3lb">
				<span class="x3s">Last Name *</span>
				<div class="x3d">
					<input type="text" class="x3in" name="zyln" value="<?php echo $zyln; ?>" id="zyln">
				</div>
			</label>
			<label class="x3lb">
				<span class="x3s">Email *</span>
				<div class="x3d">
					<input type="email" class="x3in" name="zyez" value="<?php echo $zyez; ?>" id="zyez">
				</div>
			</label>
			<label class="x3lb">
				<span class="x3s">Password</span>
				<div class="x3d">
					<input type="password" class="x3in" name="zypw" value="<?php echo $_POST['zypw'] ?? ''; ?>" id="zypw">
				</div>
			</label>
			<label class="x3lb">
				<span class="x3s">Phone </span>
				<div class="x3d">
					<input type="text" class="x3in" name="zypz" value="<?php echo $zypz; ?>" id="zypz">
				</div>
			</label>			
			<label class="x3lb">
				<span class="x3s">Address Line 1</span>
				<div class="x3d">
					<input type="text" class="x3in" name="zyad1" value="<?php echo $zyad1; ?>" id="zyad1">
				</div>
			</label>
			<label class="x3lb">
				<span class="x3s">Address Line 2</span>
				<div class="x3d">
					<input type="text" class="x3in" name="zyad2" value="<?php echo $zyad2; ?>" id="zyad2">
				</div>
			</label>
			<label class="x3lb">
				<span class="x3s">Address Line 3</span>
				<div class="x3d">
					<input type="text" class="x3in" name="zyad3" value="<?php echo $zyad3; ?>" id="zyad3">
				</div>
			</label>
			<label class="x3lb">
				<span class="x3s">City</span>
				<div class="x3d">
					<input type="text" class="x3in" name="zyct" value="<?php echo $zyct; ?>" id="zyct">
				</div>
			</label>
			<label class="x3lb">
				<span class="x3s">State</span>
				<div class="x3d">
					<select class="x3in" name="zyst" id="zyst">
						<?php echo SE_optionsGen($arr_state, $zyst); ?>
					</select>
				</div>
			</label>
			<div class="x3lb">
				<span class="x3s">ZIP Code</span>
				<div class="x3d">
					<input type="text" class="x3in" name="zyzp" id="zyzp" value="<?php echo $zyzp; ?>" >
				</div>
			</div>
			<label class="x3lb">
				<span class="x3s">Status</span>
				<div class="x3d">
					<select class="x3in" name="zyaz" id="zyaz">
					<?php echo SE_optionsGen(["Block","Active"], $zyaz); ?>
					</select>
				</div>
			</label>
			<div class="x3lb">
				<span class="x3s">&nbsp;</span>
				<div class="x3d x9e">
				<input type="button" value="Update" class="x3in x3in2" name="zysent" id="zysent">
				<input type="hidden" id="zyid" name="zyid" value="<?php echo $_POST['zyid']; ?>">
				<input type="hidden" name="post" value="1">
				</div>
			</div>
		</fieldset>	
	</form>
	</div>
<?php  
$msgno = "";
if(in_array(TRUE, $err)){
	$arrlen = count($err);
	for($i=0;$i<$arrlen;$i++){
		if($err[$i]) $msgno.=" e".$i;
	}
}
?>
<input type="hidden" id="msgno" value="<?php echo $msgno; ?>">