<?php  
include "ADM_SESS.php";
$err = array(FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE);
//$ermsg = "";
date_default_timezone_set("Europe/London");
$OK = FALSE;
function SE_optionsGen($array,$selected,$start=0,$end=0) {
	$end = $end==0 ? count($array)-1 : $end;
	$out = "";
	$selected = intval($selected);
	for($i=$start;$i<=$end;$i++){
		$out.= '<option value="'.$i.'"';
		$out.= $selected==$i ? ' selected ' : '' ;
		$out.= '>'.$array[$i].'</option>';
	}
	return $out;
}
function imgz( $x,$w,$h, $l ) {
    /*if (!file_exists($filename)) {
        throw new InvalidArgumentException('File "'.$filename.'" not found.');
    }*/
	    switch ($x) {
	        case 'jpeg':
	        case 'jpg':
	            $newimg = imagecreatefromjpeg($l);
	            $newimg = imagescale($newimg,$w,$h);
	            //watermark
 					//	$textcolor = imagecolorallocate($newimg, 0, 0, 0);
 					//	imagestring($newimg, 5, ($w-170), ($h-40), 'ozusedguns.com.au', $textcolor);
	            imagejpeg($newimg,$l);
	            imagedestroy($newimg);
	        break;
	
	        case 'png':
	            //$newimg = imagecreatefrompng($l);
					$newimg = imagecreatefrompng($l);
	            $newimg = imagescale($newimg,$w,$h);
					$bg = imagecreatetruecolor($w, $h);
					imagealphablending($bg, false);
 						imagesavealpha($bg, true);
					imagefill($bg, 0, 0, imagecolorallocate($bg, 255, 255, 255));
					imagecopy($bg, $newimg, 0, 0, 0, 0, $w, $h);
					imagedestroy($newimg);
					//watermark
 					//	$textcolor = imagecolorallocate($bg, 0, 0, 0);
 					//	imagestring($bg, 5, ($w-170), ($h-40), 'ozusedguns.com.au', $textcolor);   
	            imagepng($bg,$l);
	            imagedestroy($bg);
	        break;
	
	        case 'gif':
	            $newimg = imagecreatefromgif($l);
	            $newimg = imagescale($newimg,$w,$h);
	            //watermark
 					//	$textcolor = imagecolorallocate($newimg, 0, 0, 0);
 					//	imagestring($newimg, 5, ($w-170), ($h-40), 'ozusedguns.com.au', $textcolor);
	            imagegif($newimg,$l);
	            imagedestroy($newimg);
	        break;
	
	        default:
	            //throw new InvalidArgumentException('File "'.$x.'" is not valid jpg, png or gif image.');
	        break;
	    }
	}
function imgUp($imgArr,&$e1,&$e2,&$e3,&$e4,&$e5,$fileName="") {
	$img="";
	/*
	e1 = uploading error
	e2 = image is too small
	e3 = image size is more than 2MB
	e4 = image file extension is invalid
	e5 = move uploaded file failed
	*/
	if($imgArr["error"]!=0) $e1=TRUE;
	$ext = pathinfo($imgArr['name'], PATHINFO_EXTENSION);
	$ext = strtolower($ext);
	
	if(in_array($ext,array("jpg","jpeg","png","gif"))){

		$imd = getimagesize($imgArr["tmp_name"]);
		// size = width = height
		$size = 800;
		// too small image
		if($imd[0]<$size || $imd[1]<$size) $e2=TRUE;
		elseif($imgArr["size"] > 5242880) $e3=TRUE;
		else{
			if($ext=='jpeg') $ext = 'jpg';
			if(empty($fileName)) $img = date('Ymdhis').mt_rand().".".$ext;
			else $img = $fileName.".".$ext;
			$l = "../items/".$img;
			$ok = move_uploaded_file($imgArr["tmp_name"],$l);
			if($ok){
				imgz($ext,$size,$size,$l);
			}else $e5=TRUE;
			//if($ok) header("Location:upload-picture.php?ok=1");
		}	
	// invalid type of image
	}else $e4=TRUE;
	return $img;
}

    $sc = $db->prepare("SELECT `cid`, `cn` FROM `categories` WHERE `az`=? AND `scid`=?");
	$sc->execute([1,0]);
	$cat = $sc->fetchAll();
	$arr_cat = array();
	foreach($cat as $rc){
		$arr_cat[$rc['cid']]=$rc['cn'];
	}
	
	$p = $db->prepare("SELECT * FROM `items` WHERE `idz`=?");
	$p->execute([$_POST['zyid']]);
	if($r = $p->fetch()){

		if(isset($_POST['post'])){
			
			$iz = "";
	/*
		Errors
		=======================
		
		0 - Item name empty
		1 - Price empty
		2 - Invalid category
		3 - IMG 1 - Something is wrong with image uploading report to admin
		4 - IMG 1 - Uploaded image width or height is too small
		5 - IMG 1 - Uploaded image file size is too large 
		6 - IMG 1 - Invalid extension 
		7 - page name is empty
		8 - Invalid Page name
	*/		
	
			
			$err[0] = empty($_POST['zyna']) ? TRUE : FALSE;
			$err[1] = empty($_POST['zypr']) ? TRUE : FALSE;
			$err[2] = empty($_POST['zyca']) ? TRUE : FALSE;
			
			//-- generated by robotcoding3_SEYOL --//
			$zyna = $_POST['zyna'];
			$zycd = $_POST['zycd'];
			$zyca = $_POST['zyca'];
			$zypr = $_POST['zypr'];
			$zyvo = $_POST['zyvo'];
			$zype = $_POST['zype'];
			$zyco = $_POST['zyco'];
			$zybr = $_POST['zybr'];
			$zymt = $_POST['zymt'];
			$zymd = $_POST['zymd'];
			$zyaz = $_POST['zyaz'];
			$zyuz = $_POST['zyuz'];
            $zysubca = $_POST['zysubca'] ?? Null;
            if ($zysubca == Null){
                $zysubsubca = Null;
            }else{
                $zysubsubca = $_POST['zysubsubca'] ?? Null;
            }
			$zyuz = trim($zyuz);
			$zyuz = strtolower($zyuz);
			$zyuz = str_replace('"','',$zyuz);
			$zyuz = str_replace("'",'',$zyuz);
			$zyuz = str_replace('.','',$zyuz);
			$zyuz = str_replace(',','',$zyuz);
			$zyuz = str_replace(' ','-',$zyuz);
			$zyuz = str_replace('|','-',$zyuz);
			$zyuz = str_replace('_','-',$zyuz);
			
			$err[7] = empty($_POST['zyuz']) ? TRUE : FALSE;

			if(isset($_FILES["zyiz"]) && !empty($_FILES["zyiz"]['name'])){
				$iz = imgUp($_FILES["zyiz"],$err[3],$err[4],$err[5],$err[6],$err[3],$r['uz']);
			}
						
			
			if(!in_array(TRUE, $err)){
				if(!empty($r['iz']) && !empty($iz)) unlink('../items/'.$r['iz']);
				$iz = empty($iz) ? $r['iz'] : $iz;
				//-- generated by robotcoding2_SEYOL --//
					$OK = $db->prepare("UPDATE `items` SET `na`=?, `cd`=?, `ca`=?,`sid`=?,`ssid`=?, `pr`=?, `vo`=?, `pe`=?, `co`=?, `br`=?, `mt`=?, `md`=?, `iz`=?, `az`=?, `uz`=? WHERE `idz`=?")->execute([$zyna, $zycd, $zyca,$zysubca,$zysubsubca, $zypr, $zyvo, $zype, $zyco, $zybr, $zymt, $zymd, $iz, $zyaz, $zyuz, $_POST['zyid']]);
			}
		}else{
			//-- generated by robotcoding1_SEYOL --//

            $ssc = $db->prepare("SELECT `cid`, `cn` FROM `categories` WHERE `az`=? AND  `scid`=?");
            $ssc->execute([1,$r['ca']]);
            $scat = $ssc->fetchAll();
            $arr_scat = array();
            foreach($scat as $src){
                $arr_scat[$src['cid']]=$src['cn'];
            }

            $sssc = $db->prepare("SELECT `cid`, `cn` FROM `categories` WHERE `az`=? AND  `ssid`=?");
            $sssc->execute([1,$r['sid']]);
            $sscat = $sssc->fetchAll();
            $arr_sscat = array();
            foreach($sscat as $ssrc){
                $arr_sscat[$ssrc['cid']]=$ssrc['cn'];
            }



				$zyna = $r['na'];
				$zycd = $r['cd'];
				$zyca = $r['ca'];
				$zypr = $r['pr'];
				$zyvo = $r['vo'];
				$zype = $r['pe'];
				$zyco = $r['co'];
				$zybr = $r['br'];
				$zymt = $r['mt'];
				$zymd = $r['md'];
				$zyaz = $r['az'];
				$zyuz = $r['uz'];
		}
	}else echo "No records found";

 ?>


	<div id="zy1">
		<?php if($OK) echo '<div class="x3ok">The item has been updated</div>'; ?>
		<h1>Edit Item</h1>
		<form action="" method="post" enctype="multipart/form-data" id="zf1">
		<fieldset class="x3fs">
			<label class="x3lb">
				<span class="x3s">Item Name *</span>
				<div class="x3d">
					<input type="text" class="x3in" name="zyna" value="<?php echo $zyna; ?>" id="zyna">
				</div>
			</label>
			<label class="x3lb">
				<span class="x3s">Code Name</span>
				<div class="x3d">
					<input type="text" class="x3in" name="zycd" value="<?php echo $zycd; ?>" id="zycd">
				</div>
			</label>
			<label class="x3lb">
				<span class="x3s">Category *</span>
				<div class="x3d">
					<select class="x3in" name="zyca" id="zyca" onchange="myCategoryFunction()">
						<?php 
							foreach($arr_cat as $k => $v){
								echo '<option value="',$k,'"';
								echo $k==$zyca ? ' selected ' : '';
								echo '>',$v,'</option>';										
							}
						?>
					</select>
				</div>
			</label>

                <label class="x3lb" id="subcatfild" <?php if ($r['sid'] == null) { echo 'style="display: none"';}?> >
                    <span class="x3s"> Sub Category *</span>
                    <div class="x3d">
                        <select class="x3in" name="zysubca" id="subzyca" onchange="mySubCategoryFunction()">
                            <?php
                                foreach($arr_scat as $k => $v){
                                    echo '<option value="',$k,'"';
                                    echo $k==$r['sid'] ? ' selected ' : '';
                                    echo '>',$v,'</option>';
                                }
                            ?>
                        </select>
                    </div>
                </label>

            <label class="x3lb" id="subsubcatfild" <?php if ($r['ssid'] == null) { echo 'style="display: none"';}?>>
                <span class="x3s"> Sub Sub Category *</span>
                <div class="x3d">
                    <select class="x3in" name="zysubsubca" id="subsubzyca" >
                        <?php
                            foreach($arr_sscat as $k => $v){
                                echo '<option value="',$k,'"';
                                echo $k==$r['ssid'] ? ' selected ' : '';
                                echo '>',$v,'</option>';
                            }
                        ?>
                    </select>
                </div>
            </label>

			<label class="x3lb">
				<span class="x3s">Price *</span>
				<div class="x3d">
					<input type="text" class="x3in" name="zypr" value="<?php echo $zypr; ?>" id="zypr">
				</div>
			</label>
			<label class="x3lb">
				<span class="x3s">Page Name (url) *</span>
				<div class="x3d">
					<input type="text" class="x3in" name="zyuz" value="<?php echo $zyuz; ?>" id="zyuz">
				</div>
			</label>
			<div class="x3lb">
				<span class="x3s">Image (WxH : 500x500)</span>
				<div class="x3d">
					<input type="file" class="x3in" name="zyiz" id="zyiz">
				</div>
			</div>
			<label class="x3lb">
				<span class="x3s">Volume</span>
				<div class="x3d">
					<input type="text" class="x3in" name="zyvo" value="<?php echo $zyvo; ?>" id="zyvo">
				</div>
			</label>
			<label class="x3lb">
				<span class="x3s">Percentage</span>
				<div class="x3d">
					<input type="text" class="x3in" name="zype" value="<?php echo $zype; ?>" id="zype">
				</div>
			</label>
			<label class="x3lb">
				<span class="x3s">Country/Specialty</span>
				<div class="x3d">
					<input type="text" class="x3in" name="zyco" value="<?php echo $zyco; ?>" id="zyco">
				</div>
			</label>
			<label class="x3lb">
				<span class="x3s">Brand</span>
				<div class="x3d">
					<input type="text" class="x3in" name="zybr" value="<?php echo $zybr; ?>" id="zybr">
				</div>
			</label>
			<label class="x3lb">
				<span class="x3s">SEO Title</span>
				<div class="x3d">
					<input type="text" class="x3in" name="zymt" value="<?php echo $zymt; ?>" id="zymt">
				</div>
			</label>
			<label class="x3lb">
				<span class="x3s">SEO Description</span>
				<div class="x3d">
					<input type="text" class="x3in" name="zymd" value="<?php echo $zymd; ?>" id="zymd">
				</div>
			</label>
			<label class="x3lb">
				<span class="x3s">Item Status</span>
				<div class="x3d">
					<select class="x3in" name="zyaz" id="zyaz">
					<?php echo SE_optionsGen(["N/A","Active","Out of Stock"], $zyaz); ?>
					</select>
				</div>
			</label>
			<div class="x3lb">
				<span class="x3s">&nbsp;</span>
				<div class="x3d x9e">
				<input type="button" value="Update" class="x3in x3in2" name="zysent" id="zysent">
				<input type="hidden" value="1" name="post">
				</div>
			</div>
		</fieldset>	
		<input type="hidden" id="zyid" name="zyid" value="<?php echo $_POST['zyid']; ?>">
	</form>
	</div>
<?php  
$msgno = "";
if(in_array(TRUE, $err)){
	$arrlen = count($err);
	for($i=0;$i<$arrlen;$i++){
		if($err[$i]) $msgno.=" e".$i;
	}
}
?>
<input type="hidden" id="msgno" value="<?php echo $msgno; ?>">