<?php  
include "ADM_SESS.php";
date_default_timezone_set("Europe/London");
	$p = $db->prepare("SELECT * FROM `orders` WHERE `oid`=?");
	$p->execute([$_POST['zyid']]);
	if($r = $p->fetch()){
		//-- generated by robotcoding1_SEYOL --//
		$zybfn = $r['bfn'];
		$zybln = $r['bln'];
		$zybad1 = $r['bad1'];
		$zybad2 = $r['bad2'];
		$zybad3 = $r['bad3'];
		$zybpz = $r['bpz'];
		$zybzp = $r['bzp'];
		$zybct = $r['bct'];
		$zybst = $r['bst'];
		$zybem = $r['bem'];
		$zysfn = $r['sfn'];
		$zysln = $r['sln'];
		$zysad1 = $r['sad1'];
		$zysad2 = $r['sad2'];
		$zysad3 = $r['sad3'];
		$zyspz = $r['spz'];
		$zyszp = $r['szp'];
		$zysct = $r['sct'];
		$zysst = $r['sst'];
		$zysem = $r['sem'];
		$zydt = $r['dt'];
		$pay = $r['pay'];
		$code = $r['code'];
		$amount = $r['tpr'];
	}
	$arr_status = array("Not Completed","Paid","Cancel");
 ?>
	<div id="zy1">
		<h1>View Order</h1>
		<?php //-- generated by robotcoding4_SEYOL --// ?>
		<form action="" method="post" enctype="multipart/form-data" id="zf1">
		<h2>Order Details</h2>
		<fieldset class="x3fs">
			<label class="x3lb">
				<span class="x3s">Order Status</span>
				<div class="x3d">
				<span class="x3in"><?php echo $arr_status[$r['pay']]; ?></span>
				</div>
			</label>
			<label class="x3lb">
				<span class="x3s">Transaction Code</span>
				<div class="x3d">
				<input type="hidden" value="<?php echo $code; ?>" name="code">
				<span class="x3in"><?php echo $code; ?></span>
				</div>
			</label>
			<label class="x3lb">
				<span class="x3s">Order Amount</span>
				<div class="x3d">
				<span class="x3in"><?php echo $amount; ?></span>
				</div>
			</label>
		</fieldset>	
		<h2>Shipping Details</h2>
			<fieldset class="x3fs">
			<label class="x3lb">
				<span class="x3s">First Name</span>
				<div class="x3d">
				<span class="x3in"><?php echo $zysfn; ?></span>
				</div>
			</label>
			<label class="x3lb">
				<span class="x3s">Last Name</span>
				<div class="x3d">
				<span class="x3in"><?php echo $zysln; ?></span>
				</div>
			</label>
			<label class="x3lb">
				<span class="x3s">Address</span>
				<div class="x3d">
				<span class="x3in"><?php echo $zysad1,'<br>',$zysad2,'<br>',$zysad3; ?></span>
				</div>
			</label>
			<label class="x3lb">
				<span class="x3s">Phone No</span>
				<div class="x3d">
				<span class="x3in"><?php echo $zyspz; ?></span>
				</div>
			</label>
			<label class="x3lb">
				<span class="x3s">Zip Code</span>
				<div class="x3d">
				<span class="x3in"><?php echo $zyszp; ?></span>
				</div>
			</label>
			<label class="x3lb">
				<span class="x3s">City</span>
				<div class="x3d">
				<span class="x3in"><?php echo $zysct; ?></span>
				</div>
			</label>
			<label class="x3lb">
				<span class="x3s">State</span>
				<div class="x3d">
				<span class="x3in"><?php echo $zysst; ?></span>
				</div>
			</label>
			<label class="x3lb">
				<span class="x3s">Email</span>
				<div class="x3d">
				<span class="x3in"><?php echo $zysem; ?></span>
				</div>
			</label>
			</fieldset>
			<h2>Billing Details</h2>
			<fieldset class="x3fs">
				<label class="x3lb">
				<span class="x3s">First Name</span>
				<div class="x3d">
				<span class="x3in"><?php echo $zybfn; ?></span>
				</div>
			</label>
			<label class="x3lb">
				<span class="x3s">Last Name</span>
				<div class="x3d">
				<span class="x3in"><?php echo $zybln; ?></span>
				</div>
			</label>
			<label class="x3lb">
				<span class="x3s">Address</span>
				<div class="x3d">
				<span class="x3in"><?php echo $zybad1,'<br>',$zybad2,'<br>',$zybad3; ?></span>
				</div>
			</label>
			<label class="x3lb">
				<span class="x3s">Phone No</span>
				<div class="x3d">
				<span class="x3in"><?php echo $zybpz; ?></span>
				</div>
			</label>
			<label class="x3lb">
				<span class="x3s">Zip Code</span>
				<div class="x3d">
				<span class="x3in"><?php echo $zybzp; ?></span>
				</div>
			</label>
			<label class="x3lb">
				<span class="x3s">City</span>
				<div class="x3d">
				<span class="x3in"><?php echo $zybct; ?></span>
				</div>
			</label>
			<label class="x3lb">
				<span class="x3s">State</span>
				<div class="x3d">
				<span class="x3in"><?php echo $zybst; ?></span>
				</div>
			</label>
			<label class="x3lb">
				<span class="x3s">Email</span>
				<div class="x3d">
				<span class="x3in"><?php echo $zybem; ?></span>
				</div>
			</label>
			<label class="x3lb">
				<span class="x3s">Date</span>
				<div class="x3d">
				<span class="x3in"><?php echo $zydt; ?></span>
				</div>
			</label>
			</fieldset>
		</form>
	</div>
